dist: bionic
language: ruby
services:
  - docker
addons:
  apt:
    packages:
    - haveged # Extra entropy
rvm:
  - jruby-9.0.5.0
  - jruby-9.1.17.0
  - jruby-9.2.7.0
before_install:
  - sudo service haveged start # Extra entropy to ensure quick start time for JRuby
  - rvm use @global
  - gem uninstall -v '>= 2' -ax bundler || true
  - gem install bundler -v '< 2'
  - docker-compose up -d
env:
  global:
    - JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -Xcext.enabled=false -J-Xss2m -Xcompile.invokedynamic=false'
script: bin/all_specs
notifications:
  email: false
