version: "3.1"

services:
  db:
    image: mysql:5.6
    volumes:
      - ./docker/ecco-my.cnf:/etc/mysql/conf.d/ecco-my.cnf
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ecco_test
